### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by persianpros**
The idea, the IPKFeedGenerator.jar tool and the shell scripts came from OV's repos.

### CODE REVIEW

**Comment by persianpros** [comment]
@jbleyel 

You may want to use https://github.com/OpenVisionE2/GioppyGio-settings too :+1:

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/oe-alliance-settings-feed/commit/fcd220faf95b9616f3975fd43f6aee9bab686546

**Comment by persianpros** [comment]
@jbleyel 

Would you please give it a run? I want to use this feed for OV too and remove settings from bitbake.

**Comment by jbleyel** [comment]
Please note !! .. the ipk filenames for gioppygio can be different as if you use bb.

**Comment by persianpros** [comment]
Yep, we don't pre-install any channel settings :+1: 

There are more to add like http://matzesetting.brinkster.net

**Comment by jbleyel** [comment]
Matze settings are different because there is no github repro.
I can add matze If you make a github repro like gio.

**Comment by persianpros** [comment]
Ok give me some time :+1:

**Comment by jbleyel** [comment]
Or you make a shell script what we can use here for matze.
Please note !! we need something like a hash to check if the settings has been changed.

**Comment by jbleyel** [comment]
This should be not that problem because you can download the zip from the website and then extract the zip to use it like the other settings.

**Comment by jbleyel** [comment]
The hash can be the zip md5 ;-)

**Comment by jbleyel** [comment]
I have checked the zip files .. the zip has only a ipk inside what we can use.
I think we do not need to recreate the ipk.

**Comment by persianpros** [comment]
If the zip file provides the ipk only then we can fetch the ipk directly as he provides the ipk too right?

**Comment by jbleyel** [comment]
yes .. download zip and extract the ipk from the zip

**Comment by jbleyel** [comment]
http://matzesetting.brinkster.net/db/online_update/gp3_e2/enigma2-plugin-settings-sat-matzesetting-astra-hotbird_210919_all.zip

http://matzesetting.brinkster.net/db/online_update/gp3_e2/enigma2-plugin-settings-sat-matzesetting-astra-hotbird-lamedb_210919_all.zip

http://matzesetting.brinkster.net/db/enigma_2_kabel-deutschland_matze.zip

**Comment by persianpros** [comment]
I mean http://matzesetting.brinkster.net/db/enigma_2_astra-hb_matze.zip and http://matzesetting.brinkster.net/db/enigma_2_astra_matze.zip which are always the same, for those links you need the date as well.

**Comment by jbleyel** [comment]
NO .. these zip files contains deb

**Comment by persianpros** [comment]
We can use Packages.gz from http://matzesetting.brinkster.net/db/online_update/gp3_e2/ right?

**Comment by jbleyel** [comment]
> We can use Packages.gz from http://matzesetting.brinkster.net/db/online_update/gp3_e2/ right?

I prefer zip download.

**Comment by jbleyel** [comment]
http://matzesetting.brinkster.net/db/enigma_2_astra-hb_matze.zip
http://matzesetting.brinkster.net/db/enigma_2_astra_matze.zip
http://matzesetting.brinkster.net/db/enigma_2_kabel-deutschland_matze.zip

Download , extract , create ipk

**Comment by persianpros** [comment]
@jbleyel 

https://github.com/OpenVisionE2/Matze-settings

**Comment by jbleyel** [comment]
Please check this.
[control.tar.gz](https://github.com/oe-alliance/oe-alliance-settings-feed/files/7194596/control.tar.gz)

I like this update feature from matze.

**Comment by persianpros** [comment]
Check https://github.com/OpenVisionE2/Matze-settings again, I think now it's a fine repo.

**Pull request merged**
